# Generated by Django 4.0.3 on 2022-03-17 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strugglebusapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('date', models.DateField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strugglebusapi.post')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strugglebusapi.rider')),
            ],
        ),
    ]
